/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bureau.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bureau(props) {
  const { nodes, materials } = useGLTF('/bureau3D/bureau.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ikea_office_workplace_5.geometry} material={nodes.ikea_office_workplace_5.material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/bureau3D/bureau.gltf')
