/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 red_house.gltf 
Author: MrdT (https://sketchfab.com/mrdt.club)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-house-019efdeb6c3a4dc698fab39c8aa12b7d
Title: Red House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Red_house(props) {
  const { nodes, materials } = useGLTF('/red_house.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials.Color_A11} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials.Color_A13} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials.Color_A04} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_A08} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Color_A10} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials.Color_A05} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials.Color_007} />
        <mesh geometry={nodes.Material2_9.geometry} material={materials.Polished_Concrete_New} />
        <mesh geometry={nodes.Material3.geometry} material={materials.Vegetation_Grass_Artificial} />
        <mesh geometry={nodes.Material2_10.geometry} material={materials.Color_A03} />
        <mesh geometry={nodes.Material2_11.geometry} material={materials.Color_A14} />
        <mesh geometry={nodes.Material2_12.geometry} material={materials['2420x1']} />
        <mesh geometry={nodes.Material2_13.geometry} material={materials['2420x1200']} />
        <mesh geometry={nodes.Material2_14.geometry} material={materials['2420x1200_14']} />
        <mesh geometry={nodes.Material2_15.geometry} material={materials.afu321_230314081130793} />
        <mesh geometry={nodes.Material2_16.geometry} material={materials.afu321_230313173527603} />
        <mesh geometry={nodes.Material2_17.geometry} material={materials.afu321_230313183341407} />
        <mesh geometry={nodes.Material2_18.geometry} material={materials.Steel_Brushed_Stainless} />
        <mesh geometry={nodes.Material2_19.geometry} material={materials['2420x1200_0']} />
        <mesh geometry={nodes.Material2_20.geometry} material={materials.Roofing_Metal_Standing_Seam_Red} />
        <mesh geometry={nodes.Material3_1.geometry} material={materials.Roofing_Tile_Spanish} />
        <mesh geometry={nodes.Material2_21.geometry} material={materials.afu321_230316073147609} />
        <mesh geometry={nodes.Material2_22.geometry} material={materials.afu321_230314092423858} />
        <mesh geometry={nodes.Material2_23.geometry} material={materials.Concrete_Form_4x8} />
        <mesh geometry={nodes.Material2_24.geometry} material={materials.afu321_230304101404212} />
        <mesh geometry={nodes.Material2_25.geometry} material={materials.Brick_Antique_01} />
        <mesh geometry={nodes.Material2_26.geometry} material={materials['2420x1200_27']} />
        <mesh geometry={nodes.Material2_27.geometry} material={materials['2420x1200_28']} />
        <mesh geometry={nodes.Material2_28.geometry} material={materials.afu321_230304111952983} />
        <mesh geometry={nodes.Material2_29.geometry} material={materials.afu321_230316073147609_1} />
        <mesh geometry={nodes.Material2_30.geometry} material={materials.Cladding_Stucco_White} />
        <mesh geometry={nodes.Material2_31.geometry} material={materials.afu321_230316073122076} />
        <mesh geometry={nodes.Material2_32.geometry} material={materials.afu321_230315073207993} />
        <mesh geometry={nodes.Material2_33.geometry} material={materials.Carpet_Plush_Charcoal} />
        <mesh geometry={nodes.Material2_34.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2_35.geometry} material={materials.afu321_230311145600050} />
        <mesh geometry={nodes.Material2_36.geometry} material={materials.afu321_230311145600050} />
        <mesh geometry={nodes.Material2_37.geometry} material={materials['2420x1200_1']} />
        <mesh geometry={nodes.Material2_38.geometry} material={materials.afu321_230314075649356} />
        <mesh geometry={nodes.Material2_39.geometry} material={materials['2420x1200_0_39']} />
        <mesh geometry={nodes.Material2_40.geometry} material={materials.afu321_230314082006844} />
        <mesh geometry={nodes.Material2_41.geometry} material={materials.afu321_230315072932303} />
        <mesh geometry={nodes.Material2_42.geometry} material={materials.afu321_230311165950103} />
        <mesh geometry={nodes.Material2_43.geometry} material={materials.afu321_230313183211721} />
        <mesh geometry={nodes.Material2_44.geometry} material={materials['2420x1200_0_44']} />
        <mesh geometry={nodes.Material2_45.geometry} material={materials['2420x1200_0_45']} />
        <mesh geometry={nodes.Material2_46.geometry} material={materials.Textile_Rug_Stripes} />
        <mesh geometry={nodes.Material2_47.geometry} material={materials.afu321_231206145627455} />
        <mesh geometry={nodes.Material2_48.geometry} material={materials.afu321_231206145627455} />
        <mesh geometry={nodes.Material2_49.geometry} material={materials.afu321_231206145627455} />
        <mesh geometry={nodes.Material2_50.geometry} material={materials.afu321_230313183341407_2} />
        <mesh geometry={nodes.Material2_51.geometry} material={materials['2420x1200_49']} />
        <mesh geometry={nodes.Material2_52.geometry} material={materials['2420x1200_3']} />
        <mesh geometry={nodes.Material2_53.geometry} material={materials.afu321_230313172022463} />
        <mesh geometry={nodes.Material3_2.geometry} material={materials.afu321_230314081923019} />
        <mesh geometry={nodes.Material2_54.geometry} material={materials['2420x1200_1_53']} />
        <mesh geometry={nodes.Material2_55.geometry} material={materials['2420x1200_1_53']} />
        <mesh geometry={nodes.Material2_56.geometry} material={materials['2420x1200_2']} />
        <mesh geometry={nodes.Material2_57.geometry} material={materials['2420x1200_55']} />
        <mesh geometry={nodes.Material2_58.geometry} material={materials['2420x1200_1_56']} />
        <mesh geometry={nodes.Material2_59.geometry} material={materials.afu321_230313173725614} />
        <mesh geometry={nodes.Material2_60.geometry} material={materials['2420x1200_58']} />
        <mesh geometry={nodes.Material2_61.geometry} material={materials.Mirror_02} />
        <mesh geometry={nodes.Material3_3.geometry} material={materials.material_14} />
        <mesh geometry={nodes.Material2_62.geometry} material={materials.material_23} />
        <mesh geometry={nodes.Material2_63.geometry} material={materials['ziliaocang.com_138661']} />
        <mesh geometry={nodes.Material2_64.geometry} material={materials.Color_003} />
        <mesh geometry={nodes.Material2_65.geometry} material={materials.Poster_IKEA} />
        <mesh geometry={nodes.Material2_66.geometry} material={materials.wood__corkboard_boarder} />
        <mesh geometry={nodes.Material2_67.geometry} material={materials.cork} />
        <mesh geometry={nodes.Material2_68.geometry} material={materials['04_timetable']} />
        <mesh geometry={nodes.Material2_69.geometry} material={materials.afu321_231109205638790} />
        <mesh geometry={nodes.Material2_70.geometry} material={materials.afu321_231109205638720} />
        <mesh geometry={nodes.Material2_71.geometry} material={materials.afu321_231109205638749} />
        <mesh geometry={nodes.Material2_72.geometry} material={materials['ziliaocang.com_vray_0010']} />
        <mesh geometry={nodes.Material2_73.geometry} material={materials.Light_Oak} />
        <mesh geometry={nodes.Material3_4.geometry} material={materials.a69b9b786373e6c286d0756988415cc6} />
        <mesh geometry={nodes.Material2_74.geometry} material={materials['Cherry_Ginger-Sable-Glaze_Vert2']} />
        <mesh geometry={nodes.Material2_75.geometry} material={materials.material_3_54} />
        <mesh geometry={nodes.Material2_76.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Material2_77.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Material2_78.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Material2_79.geometry} material={materials.material_32} />
        <mesh geometry={nodes.Material2_80.geometry} material={materials.material_31} />
        <mesh geometry={nodes.Material2_81.geometry} material={materials.material_16} />
        <mesh geometry={nodes.Material3_5.geometry} material={materials.keyboard} />
        <mesh geometry={nodes.Material2_82.geometry} material={materials.Material_3} />
        <mesh geometry={nodes.Material2_83.geometry} material={materials.afu321_231109205638686} />
        <mesh geometry={nodes.Material2_84.geometry} material={materials.afu321_231109205638261} />
        <mesh geometry={nodes.Material2_85.geometry} material={materials.afu321_231109205638450} />
        <mesh geometry={nodes.Material2_86.geometry} material={materials.afu321_231109205638430} />
        <mesh geometry={nodes.Material2_87.geometry} material={materials.afu321_231109205638237} />
        <mesh geometry={nodes.Material2_88.geometry} material={materials.Color_A05_1} />
        <mesh geometry={nodes.Material2_89.geometry} material={materials.material_60} />
        <mesh geometry={nodes.Material2_90.geometry} material={materials.material_61} />
        <mesh geometry={nodes.Material2_91.geometry} material={materials.material_62} />
        <mesh geometry={nodes.Material2_92.geometry} material={materials.material_66} />
        <mesh geometry={nodes.Material2_93.geometry} material={materials.material_67} />
        <mesh geometry={nodes.Material2_94.geometry} material={materials.material_63} />
        <mesh geometry={nodes.Material2_95.geometry} material={materials.material_64} />
        <mesh geometry={nodes.Material2_96.geometry} material={materials.material_65} />
        <lineSegments geometry={nodes.Material3_6.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_7.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_8.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_9.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material4.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material4_1.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_10.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_11.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_12.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_13.geometry} material={materials.Merged_materials} />
        <lineSegments geometry={nodes.Material3_14.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_97.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_98.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_99.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_100.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material3_15.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material3_16.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_101.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_102.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_103.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_104.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_105.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_106.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_107.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_108.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_109.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_110.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_111.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_112.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_113.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_114.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_115.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_116.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_117.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_118.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_119.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_120.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material3_17.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_121.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material3_18.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_122.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_123.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_124.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_125.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_126.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_127.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_128.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_129.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_130.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material3_19.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material3_20.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material11.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_131.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material2_132.geometry} material={materials.Merged_materials} />
        <mesh geometry={nodes.Material3_21.geometry} material={materials.Merged_materials} />
      </group>
    </group>
  )
}

useGLTF.preload('/red_house.gltf')
