/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 white_house.gltf 
Author: Bogdan Strielecki (https://sketchfab.com/strielecki)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/suburban-house-efcc220c62f641d29a1480e8b221c7b3
Title: Suburban House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function White_house (props) {
  const { nodes, materials } = useGLTF('/white_house/white_house.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group position={[9121.002, 2181.975, 6732.132]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.white_white_0.geometry} material={materials.white} />
          <mesh geometry={nodes.white_white_0_1.geometry} material={materials.white} />
        </group>
        <mesh geometry={nodes.siding_siding_0.geometry} material={materials.siding} position={[6703.238, 2336.996, 4287.344]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.roof_roof_0.geometry} material={materials.roof} position={[6297.113, 4427.766, 3346.677]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['gray_������������_-_������������-_0'].geometry} material={materials.material} position={[11451.243, 889.643, 8122.147]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.glass_glass_0.geometry} material={materials.glass} position={[6851.304, 3100, 2721.197]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.floor_floor_0.geometry} material={materials.floor} position={[8990.184, -251.863, 6732.605]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/white_house/white_house.gltf')
